/* eslint-disable global-require */
const images = {
  avatar: require('../../assets/images/avatar.png'),
  piala: require('../../assets/images/piala.png'),
  logo: require('../../assets/images/logo.png'),
  logo2: require('../../assets/images/logo2.png'),
  logoTelkom: require('../../assets/images/logoTelkom.png'),
  logoDesc: require('../../assets/images/logoDesc.png'),
  setting: require('../../assets/images/setting.png'),
  garis: require('../../assets/images/garis.png'),
  deskripsi: require('../../assets/images/deskripsi.png'),
  background: require('../../assets/images/background.png'),
  background2: require('../../assets/images/background2.png'),
  backgroundv2: require('../../assets/images/backgroundv2.png'),
  bab1: require('../../assets/images/buttonbab1.png'),
  bab2: require('../../assets/images/buttonbab2.png'),
  bab3: require('../../assets/images/buttonbab3.png'),
  bab4: require('../../assets/images/buttonbab4.png'),
  bab5: require('../../assets/images/buttonbab5.png'),
  bab6: require('../../assets/images/buttonbab6.png'),
  creator1: require('../../assets/images/putri.png'),
  creator2: require('../../assets/images/yesica.png'),
  creator3: require('../../assets/images/rizal.png'),
  creator4: require('../../assets/images/salma.png'),
  creator5: require('../../assets/images/viona.png'),
  previous: require('../../assets/images/previous.png'),
  next: require('../../assets/images/next.png'),
  buttonSelesai: require('../../assets/images/btnSelesai.png'),
  buttonTutup: require('../../assets/images/btnTutup.png'),
  buttonKuis: require('../../assets/images/btnKuis.png'),
  buttonTentang: require('../../assets/images/btnTentangKami.png'),
  buttonArtikel: require('../../assets/images/btnArtikel.png'),
  buttonMasuk: require('../../assets/images/btnMasuk.png'),
  buttonLogout: require('../../assets/images/btnLogout.png'),
  buttonDaftar: require('../../assets/images/btnDaftar.png'),
  buttonLatSoal: require('../../assets/images/btnLatihanSoal.png'),
  buttonUjian: require('../../assets/images/btnUjian.png'),
  buttonBack: require('../../assets/images/ButtonBack.png'),
  buttonMateri: require('../../assets/images/btnMateri.png'),
  buttonVideo: require('../../assets/images/btnVideo.png'),
  garuda: require('../../assets/images/garuda.jpg')
};

export default images;
